apiVersion: apps/v1
kind: Deployment
metadata:
  name: megasecond
spec:
  replicas: 1
  selector:
    matchLabels:
      app: megasecond
  template:
    metadata:
      labels:
        app: megasecond
    spec:
      volumes:
        - { name: dist, emptyDir: {} }
      containers:
        - name: megasecond
          image: bang5:5000/megasecond_image
          volumeMounts:
            - { name: dist, mountPath: /workspace/dist }
          ports: [{ containerPort: 10001 }]
        - name: rebuild-client
          image: bang5:5000/megasecond_image
          volumeMounts:
            - { name: dist, mountPath: /workspace/dist }
          command: ["pnpm", "rebuild_client_forever"]

---
apiVersion: v1
kind: Service
metadata:
  name: megasecond
spec:
  ports:
    - { port: 80, targetPort: 10001, name: http }
  selector:
    app: megasecond
