apiVersion: apps/v1
kind: Deployment
metadata:
  name: megasecond
spec:
  replicas: 1
  selector:
    matchLabels:
      app: megasecond
  template:
    metadata:
      labels:
        app: megasecond
    spec:
      volumes:
        - { name: rollup-build, emptyDir: {} }
      containers:
        - name: megasecond
          image: bang5:5000/megasecond_image
          volumeMounts:
            - { name: rollup-build, mountPath: /workspace/rollup_build }
          command: ["server/run_server.sh"]
          ports: [{ containerPort: 10001}, {containerPort: 9002 }]
          env:
            - name: DEBUG
              value: colyseus:matchmaking
        # this container reads from client/** and outputs to rollup_build/
        - name: rebuild-client
          image: bang5:5000/megasecond_image
          volumeMounts:
            - { name: rollup-build, mountPath: /workspace/rollup_build }
          command: ["server/rebuild_client_forever.sh"]
          ports: [{ containerPort: 9001 }]

---
apiVersion: v1
kind: Service
metadata:
  name: megasecond
spec:
  ports:
    - { port: 80, targetPort: 10001, name: http }
    - { port: 9001, targetPort: 9001, name: cblog }
    - { port: 9002, targetPort: 9002, name: servlog }
  selector:
    app: megasecond
