apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: megasecond
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05"
      timezone: "Local"
  artifacts:
    - image: bang5:5000/megasecond_image
      sync:
        infer:
          # Watched by ts-node-dev
          - "server/**"
          # Watched by server/ app (except index.html which won't trigger a rebuild)
          - "client/**"
deploy:
  kubectl:
    manifests:
      - deploy.yaml
