apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: megasecond
build:
  artifacts:
    - image: bang5:5000/megasecond_image
      sync:
        infer:
          - server/**
          - client/**
          - shared/**
          - client_root/**
          - build/**
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05
      timezone: Local
manifests:
  rawYaml:
    - deploy.yaml
    - ingress.yaml
deploy:
  kubectl: {}
